### ISSUE TITLE
Code changes in script result in unstable ScummVM

### ISSUE THREAD

**Issue by afreickmann** [adventurebrew/magos#4]
After compiling, ScummVM gets unstable when I trigger a subtitle twice. In this example it happens e.g. when "talking to" the blacksmith twice.

[strings.txt](https://github.com/adventurebrew/magos/files/11646671/strings.txt) german strings, added 14 lines
[scripts.txt](https://github.com/adventurebrew/magos/files/11646672/scripts.txt) (changed german code)
[scripts.txt](https://github.com/adventurebrew/magos/files/11646674/scripts.txt) (original german code)

**Comment by BLooperZ** [comment]
I think the problem might be that the new strings were added at TEXT30, but the scripts that use them are in TABLE22
I think the game loads only the strings from the matching TEXT "chunk" and the "GAMPC" texts are shared
so, please try putting the new texts (in strings.txt) either on TEXT22 or in GAMEPC

**Comment by BLooperZ** [comment]
Added error handling for detecting such cases when compiling the tables
